# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from saiteki.protobuf import saiteki_pb2 as saiteki__pb2


class SaitekiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObjectiveFunction = channel.unary_unary(
                '/Saiteki/ObjectiveFunction',
                request_serializer=saiteki__pb2.CandidateRequest.SerializeToString,
                response_deserializer=saiteki__pb2.CandidateResponse.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/Saiteki/Shutdown',
                request_serializer=saiteki__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=saiteki__pb2.ShutdownResponse.FromString,
                )


class SaitekiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObjectiveFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaitekiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObjectiveFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.ObjectiveFunction,
                    request_deserializer=saiteki__pb2.CandidateRequest.FromString,
                    response_serializer=saiteki__pb2.CandidateResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=saiteki__pb2.ShutdownRequest.FromString,
                    response_serializer=saiteki__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Saiteki', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Saiteki(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObjectiveFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Saiteki/ObjectiveFunction',
            saiteki__pb2.CandidateRequest.SerializeToString,
            saiteki__pb2.CandidateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Saiteki/Shutdown',
            saiteki__pb2.ShutdownRequest.SerializeToString,
            saiteki__pb2.ShutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
