# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saiteki.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='saiteki.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rsaiteki.proto\"2\n\x10\x43\x61ndidateRequest\x12\x1e\n\nparameters\x18\x01 \x03(\x0b\x32\n.Parameter\"~\n\tParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x0bint32_value\x18\x02 \x01(\x05H\x00\x12\x15\n\x0bint64_value\x18\x03 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x02H\x00\x12\x16\n\x0cstring_value\x18\x05 \x01(\tH\x00\x42\x06\n\x04type\"\"\n\x11\x43\x61ndidateResponse\x12\r\n\x05score\x18\x01 \x01(\x02\"\x11\n\x0fShutdownRequest\"\x12\n\x10ShutdownResponse2v\n\x07Saiteki\x12:\n\x11ObjectiveFunction\x12\x11.CandidateRequest\x1a\x12.CandidateResponse\x12/\n\x08Shutdown\x12\x10.ShutdownRequest\x1a\x11.ShutdownResponseb\x06proto3'
)




_CANDIDATEREQUEST = _descriptor.Descriptor(
  name='CandidateRequest',
  full_name='CandidateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameters', full_name='CandidateRequest.parameters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=67,
)


_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Parameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int32_value', full_name='Parameter.int32_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int64_value', full_name='Parameter.int64_value', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='Parameter.float_value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='Parameter.string_value', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='Parameter.type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=69,
  serialized_end=195,
)


_CANDIDATERESPONSE = _descriptor.Descriptor(
  name='CandidateResponse',
  full_name='CandidateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='CandidateResponse.score', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=231,
)


_SHUTDOWNREQUEST = _descriptor.Descriptor(
  name='ShutdownRequest',
  full_name='ShutdownRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=250,
)


_SHUTDOWNRESPONSE = _descriptor.Descriptor(
  name='ShutdownResponse',
  full_name='ShutdownResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=270,
)

_CANDIDATEREQUEST.fields_by_name['parameters'].message_type = _PARAMETER
_PARAMETER.oneofs_by_name['type'].fields.append(
  _PARAMETER.fields_by_name['int32_value'])
_PARAMETER.fields_by_name['int32_value'].containing_oneof = _PARAMETER.oneofs_by_name['type']
_PARAMETER.oneofs_by_name['type'].fields.append(
  _PARAMETER.fields_by_name['int64_value'])
_PARAMETER.fields_by_name['int64_value'].containing_oneof = _PARAMETER.oneofs_by_name['type']
_PARAMETER.oneofs_by_name['type'].fields.append(
  _PARAMETER.fields_by_name['float_value'])
_PARAMETER.fields_by_name['float_value'].containing_oneof = _PARAMETER.oneofs_by_name['type']
_PARAMETER.oneofs_by_name['type'].fields.append(
  _PARAMETER.fields_by_name['string_value'])
_PARAMETER.fields_by_name['string_value'].containing_oneof = _PARAMETER.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['CandidateRequest'] = _CANDIDATEREQUEST
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['CandidateResponse'] = _CANDIDATERESPONSE
DESCRIPTOR.message_types_by_name['ShutdownRequest'] = _SHUTDOWNREQUEST
DESCRIPTOR.message_types_by_name['ShutdownResponse'] = _SHUTDOWNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CandidateRequest = _reflection.GeneratedProtocolMessageType('CandidateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CANDIDATEREQUEST,
  '__module__' : 'saiteki_pb2'
  # @@protoc_insertion_point(class_scope:CandidateRequest)
  })
_sym_db.RegisterMessage(CandidateRequest)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER,
  '__module__' : 'saiteki_pb2'
  # @@protoc_insertion_point(class_scope:Parameter)
  })
_sym_db.RegisterMessage(Parameter)

CandidateResponse = _reflection.GeneratedProtocolMessageType('CandidateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CANDIDATERESPONSE,
  '__module__' : 'saiteki_pb2'
  # @@protoc_insertion_point(class_scope:CandidateResponse)
  })
_sym_db.RegisterMessage(CandidateResponse)

ShutdownRequest = _reflection.GeneratedProtocolMessageType('ShutdownRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNREQUEST,
  '__module__' : 'saiteki_pb2'
  # @@protoc_insertion_point(class_scope:ShutdownRequest)
  })
_sym_db.RegisterMessage(ShutdownRequest)

ShutdownResponse = _reflection.GeneratedProtocolMessageType('ShutdownResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNRESPONSE,
  '__module__' : 'saiteki_pb2'
  # @@protoc_insertion_point(class_scope:ShutdownResponse)
  })
_sym_db.RegisterMessage(ShutdownResponse)



_SAITEKI = _descriptor.ServiceDescriptor(
  name='Saiteki',
  full_name='Saiteki',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=272,
  serialized_end=390,
  methods=[
  _descriptor.MethodDescriptor(
    name='ObjectiveFunction',
    full_name='Saiteki.ObjectiveFunction',
    index=0,
    containing_service=None,
    input_type=_CANDIDATEREQUEST,
    output_type=_CANDIDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Shutdown',
    full_name='Saiteki.Shutdown',
    index=1,
    containing_service=None,
    input_type=_SHUTDOWNREQUEST,
    output_type=_SHUTDOWNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAITEKI)

DESCRIPTOR.services_by_name['Saiteki'] = _SAITEKI

# @@protoc_insertion_point(module_scope)
